### ISSUE TITLE
AI summarizer failed to create session 

### ISSUE THREAD

**Issue by eyalzoref** [explainers-by-googlers/writing-assistance-apis#1]
**Issue Description:**

When calling await ai.summarizer.create();
Throws exception: 
Uncaught InvalidStateError: The session cannot be created.

When running await ai.summarizer.capabilities(); available='after-download'

Expected: available should be equals to 'readily'.
Actual: Also after 10 mins, still available is 'after-download'.

**Environment:**
OS: Mac Book Air M1, macOS 14.5
Chrome:  Canary version 129.0.6644.0

**Comment by domenic** [comment]
This appears to be a bug report against Chromium, and not related to this explainer. Please file such bugs at https://crbug.com.
